package edu.spaced.net.message;

import java.util.List;

import com.esotericsoftware.kryonet.Connection;

import edu.spaced.net.listener.JoinListener;
import edu.spaced.simulation.entity.Player;

/**
 * Network message generated by a player joining a game/server.
 * 
 * @author Logan Lowell
 *
 */
public class JoinMessage extends NetMessage {
	public Player player;

	@Override
	public void publish(Connection connection, List<Object> listeners) {
		// Publish to all listeners
		for (Object listener : listeners) {
			((JoinListener)listener).playerJoined(connection.getID(), player);
		}
	}
}